### ISSUE TITLE
Align API spec format with the latest Commonalities agreements

### ISSUE THREAD

**Issue by jpengar** [camaraproject/HomeDevicesQoD#33]
Align API spec format with the latest Commonalities agreements:

- Commonalities - adjust the error `status` field, which will eventually be an integer (not a patterned string): PR [#145](https://github.com/camaraproject/WorkingGroups/pull/145).
- Commonalities - adjust the schema references in the errors responses and apply the agreed solution: Issue [#151](https://github.com/camaraproject/WorkingGroups/issues/151) & PR [#162](https://github.com/camaraproject/WorkingGroups/pull/162). 
- Commonalities - change the format of the API fields to lowerCamelCase: Issue [#157](https://github.com/camaraproject/WorkingGroups/issues/157), Discussion [#169](https://github.com/camaraproject/WorkingGroups/discussions/169) & PR [#171](https://github.com/camaraproject/WorkingGroups/pull/171).

**Comment by jpengar** [comment]
Addressed at https://github.com/camaraproject/HomeDevicesQoD/pull/34

**Comment by monamok** [comment]
[PR#34](https://github.com/camaraproject/HomeDevicesQoD/pull/34) was approved and merged.
