### ISSUE TITLE
GSMA OGW Product WS - Home Devices QoD formal request

### ISSUE THREAD

**Issue by jgarciahospital** [camaraproject/HomeDevicesQoD#50]
**Problem description**
Formal inclusion of the GSMA OGW Product WS request to develop a Home Devices QoD service API

**Possible evolution**
N/A

**Alternative solution**
N/A

**Additional context**
This request just formalize the inclusion of this service as part of Open Gateway innitiative, no changes expected. Formal request includes original scope of the camara subgroup, with aligned/updated language. More details in the formal request file, attached
[Camara Submission - HomeQoD_v2.docx](https://github.com/camaraproject/HomeDevicesQoD/files/12092347/Camara.Submission.-.HomeQoD_v2.docx)

**Comment by jpengar** [comment]
Close this issue and move it to Discussions, as there is no action required to resolve it. We can just treat it as a general discussion/announcement. https://github.com/camaraproject/HomeDevicesQoD/discussions/51
