### ISSUE TITLE
Questions over HomeDeviceQoD

### ISSUE THREAD

**Issue by ShutingQing** [camaraproject/HomeDevicesQoD#52]
Dears, I have a question over this API, may someone know the answer? Can app, the api caller, knows which router is the user's router? Or how should app know the devices that the user is allowed to adjust the bandwidth?

**Comment by jpengar** [comment]
> Dears, I have a question over this API, may someone know the answer? Can app, the api caller, knows which router is the user's router? Or how should app know the devices that the user is allowed to adjust the bandwidth?

@ShutingQing Please refer to:
https://github.com/camaraproject/HomeDevicesQoD/blob/76bc5448882bd2f39da78a7e4c60d166893adc68/code/API_definitions/home_devices_qod.yaml#L75

This API has been designed with the expectation that the API client has previously obtained a 3-legged access token that gives access to the appropriate scope of this API (`home-devices-qod-qos-write`) according to the CAMARA Authentication/Authorisation API access mechanisms. 

As part of the procedures to obtain an access token, the user and the home network are identified and authenticated (typically using network-based authentication on the telco side, based on the observed public API of the device, which would be the public IP of the home router).

Thus, the API request includes an access token associated with the user (standard `sub` field in the access token) and the Internet identifier corresponding to the home network to which the device is connected. So the user's information (the telco subscriber and resource owner) and the user's home network information are deducted from the access token. 

And the target user device is identified by the internal IP address (ipAddress field in the API request body) of that device in the home network.

**Comment by jpengar** [comment]
I'm closing this issue since there have been no further comments and it has already been clarified how the user's router and home device are identified.
