### ISSUE TITLE
how to use the camara’s api

### ISSUE THREAD

**Issue by saiyujs** [camaraproject/HomeDevicesQoD#55]
**Problem description**
how to use the camara’s api with my program?
for example, I want to get some informations from the home's modem. I will use the tr069 to get wifi info. now can i use camara’s api(HomeDevicesQoD) to implement it?

**Comment by jpengar** [comment]
@saiyujs What do you mean exactly by `I want to get some informations from the home's modem`?
And you say you want to use HomeDevicesQoD to implement it? 

Please note that the functionality provided by HomeDevicesQoD API is the one described in the API specification: 

>Service Enabling Network Function API for QoS-on-demand (QoD) control applied to devices connected to the user's home network. API clients can request to change, on demand, the desired QoS behaviour for the IP traffic corresponding to a specific user home device. The QoS behaviour is determined by the Service Class provided by the API Client, which is mapped to a DSCP value according to [RFC4594](https://datatracker.ietf.org/doc/html/rfc4594) guidelines.

Please refer to the API definition for further details:
https://editor.swagger.io/?url=https://raw.githubusercontent.com/camaraproject/HomeDevicesQoD/release-0.2.0/code/API_definitions/home_devices_qod.yaml

**Comment by saiyujs** [comment]
the Camara Project is only responsible for defining APIs？The Telecom operators or other operators responsible for providing interface implementation？such as TM Forum Open APIs. 
I haven't understand Camara Project Application scenarios. 

My job is to be responsible for reading and writing modem data. so I would like to know more about it, thanks.

**Comment by jpengar** [comment]
>the Camara Project is only responsible for defining APIs？The Telecom operators or other operators responsible for providing interface implementation？such as TM Forum Open APIs.
I haven't understand Camara Project Application scenarios.

@saiyujs What I see is that you actually have general questions and doubts about CAMARA Project and not specifically about the Home Devices QoD API. I recommend you to have a look at https://camaraproject.org/, [CAMARA Project Confluence](https://wiki.camaraproject.org/display/CAM/CAMARA+Project+Home) and [Getting Started with CAMARA](https://wiki.camaraproject.org/display/CAM/Getting+Started+with+CAMARA) and [CAMARA Q&A](https://wiki.camaraproject.org/pages/viewpage.action?pageId=393422).

CAMARA is focused on the API definitions, which is the NBI of the operators to the API consumers. It's true that there are some subprojects where some operators also provide reference implementations like in [QualityOnDemand](https://github.com/camaraproject/QualityOnDemand/blob/main/README.md).

>My job is to be responsible for reading and writing modem data. so I would like to know more about it, thanks.

I understand, but the Home Devices QoD API does not provide this functionality and there is no such use case yet. It looks to me like you are actually looking for implementation details in SBI, which would be outside the scope of the API definition.

**Comment by saiyujs** [comment]
thanks!!
