### ISSUE TITLE
Convention for file names of API definition

### ISSUE THREAD

**Issue by rartych** [camaraproject/HomeDevicesQoD#69]
**Problem description**
There is currently no guidelines for file names of API definition files in CAMARA.
The initially agreed proposal is to use the convention `api-name.yaml` as a guideline for the API definition file names.

**Expected behavior**
Change the file name to `home-devices-qod.yaml` before or as a part of release PR for M4.

**Alternative solution**
Wait for the final guidelines.

**Additional context**
See the discussion in [Commonalities](https://github.com/camaraproject/Commonalities/issues/284)

**Comment by jpengar** [comment]
I plan to address this as part of the public release PR. I think I will also update home_devices_qod_user_stories.md.

**Comment by jpengar** [comment]
To be fixed in https://github.com/camaraproject/HomeDevicesQoD/pull/70
